### ISSUE TITLE
TypeError (can't dup NilClass):

### ISSUE THREAD

**Issue by ManuelFrigerio** [ekyfauzi/active-campaign-rails#3]
Hi,

I'm using your gem and I got stuck at some point.
This is the code I use to verify user account on ActiveCampaign exists:

```
#1  def test_active_campaign(params)
#2    verified = false
#3    if params[:user][:ac_api_endpoint].present? && params[:user][:ac_api_key].present?
#4      require 'active-campaign-rails'
#5      active_campaign = ActiveCampaign.new(
#6          api_endpoint: params[:user][:ac_api_endpoint],
#7          api_key: params[:user][:ac_api_key])
#8      result = eval active_campaign.account_view
#9      verified = true if result[:result_code] == 1
#10    end
#11    verified
#12  end
```

Unfortunately I keep this getting this error `TypeError (can't dup NilClass):` for line #8.

Do you know why this happens?

Thanks

**Comment by ekyfauzi** [comment]
Hi @ManuelFrigerio, are you sure that your `api_endpoint` and `api_key` is correct?

**Comment by ManuelFrigerio** [comment]
No I'm testing it with wrong end_point and key on purpose to test it.
However, when I do that from the console I just get a json response that says there was a problem.
Any idea why that would happen?

**Comment by ekyfauzi** [comment]
Oh i see.
I think you should try to write your code something like this:

```ruby
require 'active-campaign-rails'

def test_active_campaign(params)
  verified = false
  if params[:user][:ac_api_endpoint].present? && params[:user][:ac_api_key].present?
    active_campaign = ActiveCampaign.new(
        api_endpoint: params[:user][:ac_api_endpoint],
        api_key: params[:user][:ac_api_key])
    result = eval active_campaign.account_view
    verified = true if result[:result_code] == 1
  end
  verified
rescue
  false
end
```

This method should return to false instead of errors when something wrong with the gem.

**Comment by ManuelFrigerio** [comment]
mm however this is not a perfect solution since if an error occurs with the gem is not necessarily because the user does not have an account..

**Comment by ekyfauzi** [comment]
I know this is not a perfect solution. But you can use this solution for a while.
Thanks for your report. I'm working on it right now.
If you have any better solution, please contribute to this gem. I will be glad if you do.
