### ISSUE TITLE
How to add contact to a list?

### ISSUE THREAD

**Issue by theDanielJLewis** [ekyfauzi/active-campaign-rails#5]
I've read the documentation but I keep running into problems. In the official API documentation, it says to use `p[#]: #` (where `#` is the list ID) to add the contact to a list. However, Rails won't accept that.

Here's what I use:

```
active_campaign.contact_sync(
  email: 'EMAIL-ADDRESS-HERE',
  p[3]: '3'
)
```

Here's the error I receive:

```
syntax error, unexpected ':', expecting =>
 p[3]: '3'
```

If I replace `:` with `=>`, I receive:

```
NoMethodError: undefined method `[]' for nil:NilClass
```

I suspect the same issue would occur with any other bracket-using variable.

**Comment by theDanielJLewis** [comment]
Oh, I may have finally figured it out (I was working on this for an hour before I posted). This seems to work:

```
active_campaign.contact_sync(
  email: 'EMAIL-ADDRESS-HERE',
  'p[3]' => '3'
)
```

It's strange, to me, to switch variable syntaxes like that, but I guess it's what I have to do when I use the quotation marks.

**Comment by ekyfauzi** [comment]
Hi @theDanielJLewis, I think you should read [this](http://www.activecampaign.com/api/example.php?call=contact_sync).

It's seems like strange, but that how the ActiveCampaign API works. 

You could try to write you code like this:
```ruby
active_campaign.contact_sync(
  "id" => user.active_campaign_contact_id,
  "email" => "user@email.com",
  "first_name" => "John",
  "last_name" => "Doe",
  "p[#{user.active_campaign_list_id}]" => user.active_campaign_list_id
)
```

or another way:
```ruby
list_params = {
  "#{user.active_campaign_list_id}" => user.active_campaign_list_id
}

active_campaign.contact_sync(
  "id" => user.active_campaign_contact_id,
  "email" => user.email,
  "first_name" => user.first_name,
  "last_name" => user.last_name,
  "p" => list_params
)
```

Hope that can help you.

Thanks for your report, I thought we can fix and improve this strange issue in the future. If you have any suggestion please help us to improve this gem, and we are open for your contributions.
